export type ComponentType =
  | 'Input'
  | 'InputNumber'
  | 'Select'
  | 'ApiSelect'
  | 'DatePickerSelect'
  | 'ApiAutoComplete'
  | 'ApiTreeSelect'
  | 'Checkbox'
  | 'Switch'
  | 'DatePicker'
  | 'ImageUpload'
  | 'TimePicker'
  | 'InputGroup'
