import { Tag, Tooltip } from 'ant-design-vue'
import { h } from 'vue'
import { DescItem } from '/@/components/Description'
import { InfoCircleOutlined } from '@ant-design/icons-vue'

// 风控基本信息
export const riskSchema: DescItem[] = [
  {
    field: 'model_score',
    label: '用户评分',
    render: (value) => {
      value = Number(value) * 100
      return (
        <>
          <div style={{ display: 'flex', alignItems: 'center' }}>
            <div style={{ color: 'red', marginRight: '6px' }}>{value.toFixed(2)}%</div>
            <Tooltip>
              {{
                title: () => '评分比值越小客户质量越好',
                default: () => <InfoCircleOutlined style={{ color: 'red' }} />,
              }}
            </Tooltip>
          </div>
        </>
      )
    },
  },
  {
    field: 'model_res',
    label: '风控结果',
    render: (value) => {
      const params = {
        '0': { txt: '通过', color: 'green' },
        '1': { txt: '不通过', color: 'red' },
      }
      return h(Tag, { color: params[value]?.color || 'orange' }, params[value]?.txt || '暂无建议')
    },
  },
  {
    field: 'description',
    label: '风控结果描述',
    render: (value) => value || '-',
  },
  {
    field: 'is_blacklist',
    label: '是否命中黑名单',
    render: (value) => {
      return h(Tag, { color: value ? 'red' : 'green' }, value ? '是' : '否')
    },
  },
  {
    field: 'reports',
    label: '手机号在网时长',
    render: (value) => {
      if (value && value.phone_info && value.phone_info.min_online) {
        return value.phone_info.min_online
      }
      return '-'
    },
  },
]
export const riskControlList: any = [
  {
    name: '注册报告',
    span: 8,
    key: 'cert_info',
    children: [
      {
        value: '-',
        title: '注册平台数',
        key: 'count',
        color: '',
        span: 5,
      },
      {
        value: '-',
        title: '最早认证',
        key: 'earliest_certification',
        color: '',
        span: 5,
      },
      {
        value: '-',
        title: '最早注册',
        key: 'earliest_registration',
        color: '',
        span: 5,
      },
      {
        value: '-',
        title: '最新认证',
        key: 'latest_certification',
        color: '',
        span: 5,
      },
      {
        value: '-',
        title: '最新注册',
        key: 'latest_registration',
        color: '',
        span: 5,
      },
    ],
  },
  {
    name: '逾期报告',
    span: 8,
    key: 'raw_report_xy.behavior_report_detail',
    children: [
      {
        value: '-',
        title: '近6个月M0+逾期贷款笔数',
        key: 'B22170025',
      },
      {
        value: '-',
        title: '近12个月M0+逾期贷款笔数',
        key: 'B22170026',
      },
      {
        value: '-',
        title: '近24个月M0+逾期贷款笔数',
        key: 'B22170027',
      },
      {
        value: '-',
        title: '近6个月M1+逾期贷款笔数',
        key: 'B22170028',
      },
      {
        value: '-',
        title: '近12个月M1+逾期贷款笔数',
        key: 'B22170029',
      },
      {
        value: '-',
        title: '近24个月M1+逾期贷款笔数',
        key: 'B22170030',
      },
    ],
  },
  {
    name: '行为报告',
    span: 6,
    key: 'raw_report_xy.behavior_report_detail',
    children: [
      {
        value: '-',
        title: '近1个⽉贷款笔数',
        key: 'B22170002',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近3个⽉贷款笔数',
        key: 'B22170003',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近6个⽉贷款笔数',
        key: 'B22170004',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近12个⽉贷款笔数',
        key: 'B22170005',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近24个⽉贷款笔数',
        key: 'B22170006',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近1个⽉贷款总⾦额',
        key: 'B22170007',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近3个⽉贷款总⾦额',
        key: 'B22170008',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近6个⽉贷款总⾦额',
        key: 'B22170009',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近12个⽉贷款总⾦额',
        key: 'B22170010',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近24个⽉贷款总⾦额',
        key: 'B22170011',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近1个⽉贷款机构数',
        key: 'B22170016',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近3个⽉贷款机构数',
        key: 'B22170017',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近6个⽉贷款机构数',
        key: 'B22170018',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近12个⽉贷款机构数',
        key: 'B22170019',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近24个⽉贷款机构数',
        key: 'B22170020',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近12个⽉消⾦类贷款机构数',
        key: 'B22170021',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近24个⽉消⾦类贷款机构数',
        key: 'B22170022',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近12个⽉⽹贷类贷款机构数',
        key: 'B22170023',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近24个⽉⽹贷类贷款机构数',
        key: 'B22170024',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近6个⽉累计逾期⾦额',
        key: 'B22170031',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近12个⽉累计逾期⾦额',
        key: 'B22170032',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近24个⽉累计逾期⾦额',
        key: 'B22170033',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近1个⽉失败扣款笔数',
        key: 'B22170035',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近3个⽉失败扣款笔数',
        key: 'B22170036',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近6个⽉失败扣款笔数',
        key: 'B22170037',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近12个⽉失败扣款笔数',
        key: 'B22170038',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近24个⽉失败扣款笔数',
        key: 'B22170039',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近1个⽉履约贷款总⾦额',
        key: 'B22170040',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近3个⽉履约贷款总⾦额',
        key: 'B22170041',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近6个⽉履约贷款总⾦额',
        key: 'B22170042',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近12个⽉履约贷款总⾦额',
        key: 'B22170043',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近24个⽉履约贷款总⾦额',
        key: 'B22170044',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近1个⽉履约贷款次数',
        key: 'B22170045',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近3个⽉履约贷款次数',
        key: 'B22170046',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近6个⽉履约贷款次数',
        key: 'B22170047',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近12个⽉履约贷款次数',
        key: 'B22170048',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近24个⽉履约贷款次数',
        key: 'B22170049',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '近12个⽉贷款⾦额在1k及以下的笔数',
        key: 'B22170012',
        color: '',
      },
      {
        value: '-',
        title: '近12个⽉贷款⾦额在1k-3k的笔数',
        key: 'B22170013',
        color: '',
      },
      {
        value: '-',
        title: '近12个⽉贷款⾦额在3k-10k的笔数',
        key: 'B22170014',
        color: '',
      },
      {
        value: '-',
        title: '近12个⽉贷款⾦额在1w以上的笔数',
        key: 'B22170015',
        color: '',
      },
      {
        value: '-',
        title: '正常还款订单数占贷款总订单数⽐例',
        key: 'B22170034',
        color: '',
      },
      {
        value: '-',
        title: '贷款⾏为分',
        key: 'B22170001',
        color: '',
      },
      {
        value: '-',
        title: '最近—次履约距今天数',
        key: 'B22170050',
        color: '',
      },
      {
        value: '-',
        title: '贷款⾏为置信度',
        key: 'B22170051',
        color: '',
      },
      {
        value: '-',
        title: '贷款已结清订单数',
        key: 'B22170052',
        color: '',
      },
      {
        value: '-',
        title: '信⽤贷款时⻓',
        key: 'B22170053',
        color: '',
      },
      {
        value: '-',
        title: '最近—次贷款放款时间',
        key: 'B22170054',
        color: '',
      },
    ],
  },
  {
    name: '租机行为报告',
    span: 8,
    key: 'raw_report_rent_apply',
    children: [
      {
        value: '-',
        title: '近7天申请平台数',
        key: 'd7_apply_agency_time',
        color: '',
        span: 5,
        hide: true,
      },
      {
        value: '-',
        title: '近1个月申请平台数',
        key: 'm1_apply_agency_time',
        color: '',
        span: 5,
        hide: true,
      },
      {
        value: '-',
        title: '近3个月申请平台数',
        key: 'm3_apply_agency_time',
        color: '',
        span: 5,
        hide: true,
      },
      {
        value: '-',
        title: '近6个月申请平台数',
        key: 'm6_apply_agency_time',
        color: '',
        span: 5,
        hide: true,
      },
      {
        value: '-',
        title: '近12个月申请平台数',
        key: 'm12_apply_agency_time',
        color: '',
        span: 5,
        hide: true,
      },
      {
        value: '-',
        title: '近7天申请次数',
        key: 'd7_apply_time',
        color: '',
        span: 5,
        hide: true,
      },
      {
        value: '-',
        title: '近1个月申请次数',
        key: 'm1_apply_time',
        color: '',
        span: 5,
        hide: true,
      },
      {
        value: '-',
        title: '近3个月申请次数',
        key: 'm3_apply_time',
        color: '',
        span: 5,
        hide: true,
      },
      {
        value: '-',
        title: '近6个月申请次数',
        key: 'm6_apply_time',
        color: '',
        span: 5,
        hide: true,
      },
      {
        value: '-',
        title: '近12个月申请次数',
        key: 'm12_apply_time',
        color: '',
        span: 5,
        hide: true,
      },
      {
        value: '-',
        title: '近7天夜间申请平台数',
        key: 'd7_night_apply_agency_time',
        color: '',
        span: 5,
        hide: true,
      },
      {
        value: '-',
        title: '近1个月夜间申请平台数',
        key: 'm1_night_apply_agency_time',
        color: '',
        span: 5,
        hide: true,
      },
      {
        value: '-',
        title: '近3个月夜间申请平台数',
        key: 'm3_night_apply_agency_time',
        color: '',
        span: 5,
        hide: true,
      },
      {
        value: '-',
        title: '近6个月夜间申请平台数',
        key: 'm6_night_apply_agency_time',
        color: '',
        span: 5,
        hide: true,
      },
      {
        value: '-',
        title: '近12个月夜间申请平台数',
        key: 'm12_night_apply_agency_time',
        color: '',
        span: 5,
        hide: true,
      },
      {
        value: '-',
        title: '近7天夜间申请次数',
        key: 'd7_night_apply_time',
        color: '',
        span: 5,
        hide: true,
      },
      {
        value: '-',
        title: '近1个月夜间申请次数',
        key: 'm1_night_apply_time',
        color: '',
        span: 5,
        hide: true,
      },
      {
        value: '-',
        title: '近3个月夜间申请次数',
        key: 'm3_night_apply_time',
        color: '',
        span: 5,
        hide: true,
      },
      {
        value: '-',
        title: '近6个月夜间申请次数',
        key: 'm6_night_apply_time',
        color: '',
        span: 5,
        hide: true,
      },
      {
        value: '-',
        title: '近12个月夜间申请次数',
        key: 'm12_night_apply_time',
        color: '',
        span: 5,
        hide: true,
      },
      {
        value: '-',
        title: '最近一次申请时间',
        key: 'ident_last_apply_time',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '同一身份证关联手机号数',
        key: 'ident_contain_phone_ct',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '同一手机号关联身份证数',
        key: 'phone_contain_ident_ct',
        color: '',
        span: 8,
      },
    ],
  },
  {
    name: '法院信息-个人',
    span: 6,
    key: 'raw_report_judge',
    children: [
      {
        value: [],
        title: '表格数据',
        key: 'list',
        color: '',
        hide: true,
      },
      {
        value: '-',
        title: '总条数',
        key: 'count',
        color: '',
      },
      {
        value: '-',
        title: '裁判文书数量',
        key: 'judgeDocumentCount',
        color: '',
      },
      {
        value: '-',
        title: '开庭公告信息数量',
        key: 'openCourtNoticeCount',
        color: '',
      },
      {
        value: '-',
        title: '执行公告信息数量',
        key: 'executeNoticeCount',
        color: '',
      },
      {
        value: '-',
        title: '失信公告信息数量',
        key: 'dishonestyNoticeCount',
        color: '',
      },
      {
        value: '-',
        title: '法院公告信息数量',
        key: 'courtAnnouncementCount',
        color: '',
      },
      {
        value: '-',
        title: '案件流程信息数量',
        key: 'caseProduceCount',
        color: '',
      },
      {
        value: '-',
        title: '曝光台信息数量',
        key: 'exposureCount',
        color: '',
      },
    ],
  },
  {
    name: '探针C',
    span: 8,
    key: 'raw_report_xy_c',
    children: [
      {
        value: '-',
        title: '探查结果编码',
        key: 'result_code',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '最⼤逾期⾦额',
        key: 'max_overdue_amt',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '最⻓逾期天数',
        key: 'max_overdue_days',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '最近逾期时间',
        key: 'latest_overdue_time',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '最⼤履约⾦额',
        key: 'max_performance_amt',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '最近履约时间',
        key: 'latest_performance_time',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '履约笔数',
        key: 'count_performance',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '当前逾期机构数',
        key: 'currently_overdue',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '当前履约机构数',
        key: 'currently_performance',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '异常还款机构数',
        key: 'acc_exc',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '睡眠机构数',
        key: 'acc_sleep',
        color: '',
        span: 8,
      },
    ],
  },
  {
    name: '申请多头',
    span: 8,
    key: 'raw_report_xy.apply_report_detail',
    children: [
      {
        value: '-',
        title: '申请准⼊分',
        key: 'A22160001',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '申请准⼊置信度',
        key: 'A22160002',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '申请命中机构数',
        key: 'A22160003',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '申请命中消⾦类机构数',
        key: 'A22160004',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '申请命中⽹络贷款类机构数',
        key: 'A22160005',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '机构总查询次数',
        key: 'A22160006',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '最近—次查询时间',
        key: 'A22160007',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '近1个⽉机构总查询笔数',
        key: 'A22160008',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '近3个⽉机构总查询笔数',
        key: 'A22160009',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '近6个⽉机构总查询笔数',
        key: 'A22160010',
        color: '',
        span: 8,
      },
    ],
  },
  {
    name: '信⽤报告',
    span: 8,
    key: 'raw_report_xy.current_report_detail',
    children: [
      {
        value: '-',
        title: '⽹贷授信额度',
        key: 'C22180001',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '⽹贷额度置信度',
        key: 'C22180002',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '⽹络贷款类机构数',
        key: 'C22180003',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '⽹络贷款类产品数',
        key: 'C22180004',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '⽹络贷款机构最⼤授信额度',
        key: 'C22180005',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '⽹络贷款机构平均授信额度',
        key: 'C22180006',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '消⾦贷款类机构数',
        key: 'C22180007',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '消⾦贷款类产品数',
        key: 'C22180008',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '消⾦贷款类机构最⼤授信额度',
        key: 'C22180009',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '消⾦贷款类机构平均授信额度',
        key: 'C22180010',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '消⾦建议授信额度',
        key: 'C22180011',
        color: '',
        span: 8,
      },
      {
        value: '-',
        title: '消⾦额度置信度',
        key: 'C22180012',
        color: '',
        span: 8,
      },
    ],
  },
]
