import { usePermission } from '/@/hooks/web/usePermission'
const { hasPermission } = usePermission()
export const moneyList = [
  {
    name: '在租订单总金额',
    content: '比上周增',
    value: 0,
    scale: 0,
    key: 'totalAmount',
    isTotal: false,
    type: 1,
    ifShow: hasPermission('StatisticsFinanceTotalAmount'),
    tooltip: '(含锁费、公证、增值服务、订单账单金额)',
  },
  {
    name: '在租首付总金额',
    content: '平台首付收款比例',
    value: 0,
    scale: 0,
    key: 'downPayment',
    isTotal: true,
    type: 2,
    ifShow: hasPermission('StatisticsFinanceDownPayment'),
    tooltip: '(含锁费、公证、增值服务、订单账单金额、部分还款)',
  },
  {
    name: '待收租金金额',
    content: '租金风险敞口比例',
    key: 'repayAmount',
    isTotal: true,
    value: 0,
    scale: 0,
    type: 2,
    ifShow: hasPermission('StatisticsFinanceRepayAmount'),
    tooltip: '(除去首付以及已还金额、不含逾期租金总金额)',
  },
  {
    name: '已还期数租金总额',
    content: '租金回款比例',
    key: 'repaidAmount',
    isTotal: true,
    value: 0,
    scale: 0,
    type: 2,
    ifShow: hasPermission('StatisticsFinanceRepaidAmount'),
    tooltip: '(含部分还款)',
  },
  {
    // 暂无
    name: '已结清订单总金额',
    content: '比上周增',
    isTotal: false,
    key: 'settleAmount',
    value: 0,
    scale: 0,
    type: 1,
    ifShow: hasPermission('StatisticsFinanceSettleAmount'),
  },
  {
    name: '逾期租金总金额',
    content: '逾期率',
    key: 'overdueAmount',
    isTotal: true,
    value: 0,
    scale: 0,
    type: 3,
    ifShow: hasPermission('StatisticsFinanceOverdueAmount'),
    // tooltip: '(不含部分还款)',
  },
  {
    name: '在租订单罚金总金额',
    content: '比上周增',
    key: 'penaltyAmount',
    isTotal: true,
    hide: true,
    value: 0,
    scale: 0,
    type: 1,
    ifShow: hasPermission('StatisticsFinancePenaltyAmount'),
  },
  {
    name: '在租订单已还罚金总金额',
    content: '',
    key: 'penaltyPaidAmount',
    isTotal: true,
    hide: true,
    value: 0,
    scale: 0,
    type: 1,
    ifShow: hasPermission('StatisticsFinanceRepaidAmount'),
  },
  {
    name: '已结清订单已还罚金总金额',
    content: '',
    key: 'otherSettleAmount',
    isTotal: true,
    hide: true,
    value: 0,
    scale: 0,
    type: 1,
    ifShow: hasPermission('StatisticsFinanceOtherSettleAmount'),
  },
  {
    name: '总待收金额',
    content: '',
    key: 'repayAmountTotal',
    isTotal: true,
    hide: true,
    value: 0,
    scale: 0,
    type: 1,
    ifShow: hasPermission('StatisticsFinanceRepayAmountTotal'),
  },
  {
    name: '金额逾期率',
    content: '',
    key: 'amountLv',
    isTotal: true,
    value: 0,
    scale: 0,
    type: 4,
    tooltip: '金额逾期率=逾期租金金额/总成交金额',
    ifShow: hasPermission('StatisticsFinanceAmountLv'),
  },
  // {
  //   name: '罚金减免金额',
  //   content: '',
  //   key: 'penaltyDiscountAmount',
  //   isTotal: true,
  //   hide: true,
  //   value: 0,
  //   scale: 0,
  //   type: 1,
  // },
]?.filter((item: any) => item.ifShow)
console.log(hasPermission('StatisticsFinanceAmountLv'), 'hasPermission')
export const searchFormSchema: FormSchema[] = [
  {
    field: 'rentType',
    label: '租赁类型',
    component: 'Select',
    defaultValue: '',
    colProps: { span: 5 },
    componentProps: {
      allowClear: false,
      options: [
        { label: '全部', value: '' },
        { label: '日付', value: 0 },
        { label: '周付', value: 1 },
        { label: '月付', value: 2 },
        { label: '十天', value: 4 },
      ],
    },
  },
  {
    field: 'time',
    label: '创建时间',
    component: 'RangePicker',
    componentProps: {
      valueFormat: 'YYYY-MM-DD',
      placeholder: ['开始日期', '结束日期'],
    },
    colProps: { span: 8 },
  },
]
